global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "rate_limiter"
    scrape_interval: 5s
    static_configs:
      - targets: ["rate_limiter:8000"]
    metrics_path: "/metrics"

  - job_name: "loki"
    scrape_interval: 15s
    static_configs:
      - targets: ["loki-app:3100"]
